import random
from collections import defaultdict

class NegativeSampler:
    """Samples negative candidate pairs for an S1 entity using prioritized strategy-based hard negative categories."""

    def __init__(self, target_ratio=4.0, max_per_s1=25, min_per_s1=2, seed=42, priority_order=None):
        self.target_ratio = target_ratio
        self.max_per_s1 = max_per_s1
        self.min_per_s1 = min_per_s1
        self.seed = seed
        self.rng = random.Random(seed)
        
        self.priority_order = priority_order or [
            "high_name_and_address_similarity",
            "name_conflict",
            "address_conflict",
            "high_name_similarity",
            "high_address_similarity",
            "easy_negative"
        ]

    def sample_negatives_for_s1(self, s1_id, negative_cand_ids, cands_a, cands_b, cands_c, num_positives=1):
        """Categorize and sample negatives for a single S1 entity using index strategy signals.

        Args:
            s1_id: S1 entity ID string
            negative_cand_ids: Set/list of S2/S3 candidate IDs that are NOT in ground truth
            cands_a: Set of candidate IDs generated by Suffixless Exact Name Index (Strategy A)
            cands_b: Set of candidate IDs generated by Rare Token Inverted Index (Strategy B)
            cands_c: Set of candidate IDs generated by Address & Postcode Index (Strategy C)
            num_positives: Number of positive ground truth pairs captured for this S1

        Returns:
            sampled_negative_ids: List of selected candidate IDs
            category_counts: Dict mapping category_name -> count of sampled negatives
        """
        if not negative_cand_ids:
            return [], {cat: 0 for cat in self.priority_order}

        # Categorize all negative candidates for this S1
        categorized = defaultdict(list)
        for cid in negative_cand_ids:
            in_a = cid in cands_a
            in_c = cid in cands_c
            in_b = cid in cands_b

            if in_a and in_c:
                cat = "high_name_and_address_similarity"
            elif in_a:
                cat = "name_conflict"
            elif in_c:
                cat = "address_conflict"
            elif in_b:
                cat = "high_name_similarity"
            else:
                cat = "easy_negative"

            categorized[cat].append(cid)

        # Compute desired number of negatives
        desired_count = int(round(num_positives * self.target_ratio))
        target_n = max(self.min_per_s1, min(desired_count, self.max_per_s1))

        sampled_negative_ids = []
        category_counts = {cat: 0 for cat in self.priority_order}

        # Step 1: Collect candidates category by category in priority order
        for cat in self.priority_order:
            cat_cands = categorized[cat]
            if not cat_cands:
                continue

            needed = target_n - len(sampled_negative_ids)
            if needed <= 0:
                break

            if len(cat_cands) <= needed:
                # Take all
                sampled_negative_ids.extend(cat_cands)
                category_counts[cat] += len(cat_cands)
            else:
                # Deterministically sample `needed` candidates
                self.rng.seed(hash((s1_id, cat, self.seed)) & 0xffffffff)
                chosen = self.rng.sample(cat_cands, needed)
                sampled_negative_ids.extend(chosen)
                category_counts[cat] += len(chosen)

        return sampled_negative_ids, category_counts
